const API = {
  getOpenId: '/main/getOpenId', // 获取openId
  getMobile: '/main/getMobile', // 获取手机号码
  loginSubmit: '/main/loginSubmit', // 登录接口
  checkLogin: '/customer/checkLogin', // 判断是否登录
  loginOut: '/main/loginOut', // 退出登录
  customer: '/customer/detail', // 验证登录,
  updatecustomer: '/customer/update', // 修改用户信息
  getVerifyCode: '/main/getVerifyCode ', // 获取验证码
  silder: '/menu/silder', // 获取轮播图
  saveSearchWord: '/customer/searchWord/saveSearchWord', // 保存搜索历史
  searchWordList: '/customer/searchWord/searchWordList', // 查询历史搜索列表
  delSearchWord: '/customer/searchWord/deleteSearchWord', // 删除历史搜索记录
  queryHotSearchKey: '/travel/product/queryHotSearchKey', // 查询热门搜索
  getMenu: '/menu/getMenu', // 旅游专区首页：旅游度假、本地特色tab
  typeList: '/travel/product/typeList', // 旅游类型（筛选条件）
  themeList: '/travel/product/themeList', // 旅游主题（筛选条件）
  getProList: '/travel/product/ajaxPage', // 获取旅游产品列表
  queryProductDetial: '/travel/product/queryProductDetial', // 获取产品详情（旅游）
  queryFreeTravelStock: '/travel/product/queryFreeTravelStock', // 查询自由行产品价格库存
  goodsList: '/shop/product/ajaxPageData', // 查询商品列表（名品名店）
  goodsDetail: '/shop/product/queryProduct', // 查询商品详情（名品名店）
  queryGiftActivityById: '/shop/product/queryGiftActivityById', // 查询名品名店赠送旅游的列表
  customerList: '/customer/visitor/ajaxPage', // 查询游客列表
  addCustomer: '/customer/visitor/save', // 新增游客
  // typeList: '/travel/product/typeList', // 首页旅游产品分类
  getShopList: '/shop/product/ajaxPageData',
  getProductDetail: '/shop/product/queryProduct',
  makeOrder: '/travel/order/makeOrder', // 旅游产品创建订单
  getReceiveList: '/customer/receiver/ajaxPage', // 获取收货地址
  getReceiveById: '/customer/receiver/detail', // 获取收货地址详情
  saveReceive: '/customer/receiver/save', // 保存收货地址
  setAddressDefault: '/customer/receiver/setDefault', // 设置默认地址
  delReceiver: '/customer/receiver/delete', // 删除收货人
  getCartList: '/shop/buyerCar/getCar', // 获取购物车
  addCart: '/shop/buyerCar/addItem', // 添加购物车
  delCart: '/shop/buyerCar/removeItem', // 删除购物车
  addCartCount: '/shop/buyerCar/addItem', // 增加商品数量
  minusCartCount: '/shop/buyerCar/reduceItem', // 减少商品数量
  getCartCount: '/shop/buyerCar/getCarNum', // 获取购物车数量
  calcCountPrice: '/shop/order/countPrice', // 计算订单金额
  getConfirmOrder: '/shop/order/getConfirmOrder', // 获取下单列表
  makeShopOrder: '/shop/order/makeOrder', // 创建名品名店订单
  getShopOrderList: '/shop/order/ajaxPage', // 获取名品名店订单列表
  getShopOrderDetail: '/shop/order/detail', // 获取名品名店订单详情
  queryGiftActivityList: '/shop/product/queryGiftActivityList', // 查询商品送旅游活动列表
  cancelShopOrder: '/shop/order/updateStatus', // 取消订单、申请退款
  comment: '/shop/comment/comment', // 评论
  getExpress: '/shop/order/queryLogistics', // 查看物流
  getMerchantList: '', // 获取店铺商品
  getMerchantDetail: '/merchant/detail', // 获取店铺详情
  queryShopRecommend: '/merchant/queryRecommend', // 获取店铺推荐
  queryShopSlider: '/merchant/queryShopSlider', // 查询商户轮播图
  getCommentList: '/shop/comment/ajaxPage', // 获取评论列表
  getTraCommentList: '/travel/comment/ajaxPage', // 获取旅游评论列表
  getFreight: '/shop/order/countFreightPrice', // 获取运费
  wxPay: '/wxPay/order', // 微信支付下单
  cardType: '/customer/visitor/cardType', // 查询游客证件列表
  customerDetail: '/customer/visitor/detail', // 查询游客详情
  deleteCustomer: '/customer/visitor/delete', // 删除游客
  travelOrderList: '/travel/order/ajaxPage', // 查询旅游产品订单列表
  travelDetail: '/travel/order/detail', // 查询旅游产品详情
  updateTraStatus: '/travel/order/updateStatus', // 取消订单、申请退款
  travelComment: '/travel/comment/comment', // 旅游商品评论
  saveBankCard: '/customer/bank/save', // 保存银行卡
  bankCardDetail: '/customer/bank/detail', // 银行卡详情
  queryPushMap: '/customer/queryPushMap', // 我的推广
  queryPushList: '/customer/queryPushList', // 推广列表
  queryShareProfitList: '/customer/queryShareProfitList', // 分润列表
  saveLicense: '/customer/saveLicense', // 合伙人注册
  createWxQrcode: '/qrcode/createWxQrcode', // 获取微信二维码
  queryRouteList: '/cruise/product/queryRouteList', // 查询邮轮航线
  cruiseList: '/cruise/product/ajaxPage', // 邮轮列表
  cruiseDetial: '/cruise/product/queryProductDetial', // 查询邮轮产品详情
  queryStock: '/cruise/product/queryStock', // 邮轮房间库存
  queryAboardList: '/cruise/product/queryAboardList', // 出发港口列表
  queryCruiseInfo: '/cruise/product/queryCruiseInfo', // 邮轮详情
  makeCruiseOrder: '/travel/order/makeCruiseOrder', // 邮轮下单
  saveRemark: '/customer/saveRemark', // 修改推广人备注名
  darenSettledin: '/travelTalent/settledin', // 达人入驻
  darenUpdate: '/travelTalent/update', // 达人信息修改
  traPersonDetail: '/travelTalent/detail', // 达人信息
  traPersonSave: '/travelTalent/saveLicense', // 达人认证
  licenseDetail: '/travelTalent/licenseDetail', // 查询达人认证
  talentComment: '/talentProduct/comment/ajaxPage', // 达人评论
  saveLabel: '/guidedEscort/saveLabel', // 保存服务亮点
  delLabel: '/guidedEscort/delLabel', // 删除服务亮点
  talent: '/guidedEscort/order/ajaxPage', // 查询达人订单列表
  casualLookList: '/casualLook/ajaxPage', // 随便看列表
  myCasualLookList: '/casualLook/myAjaxPage', // 我的随便看列表
  myPartnerList: '/partnerTravel/myAjaxPage', // 我发布的约伴列表
  casualLookDetail: '/casualLook/detail', // 随便看详情
  saveCasualLook: '/casualLook/save', // 保存随便看
  delCasualLook: '/casualLook/delete', // 删除随便看
  delCasualLookComment: '/casualLook/deleteComment', // 删除随便看
  commentCasualLook: '/casualLook/comment', // 评论随便看
  commentCasualLookList: '/casualLook/ajaxCommentPage', // 随便看评论列表
  likeCasualLookList: '/casualLook/like', // 喜欢不喜欢随便看
  followCasualLookList: '/customer/follow', // 关注不关注随便看、游记攻略
  partnerTypeList: '/partnerTravel/typeList', // 约伴出游类型列表
  partnerSave: '/partnerTravel/save', // 约伴出游新增
  partnerList: '/partnerTravel/ajaxPage', // 约伴列表
  partnerDetail: '/partnerTravel/detail', // 约伴详情
  partnerEditStatus: '/partnerTravel/updateStatus', // 修改状态
  partnerComment: '/partnerTravel/comment', // 约伴出游评论
  partnerCommentList: '/partnerTravel/ajaxCommentPage', // 约伴出游评论列表
  partnerDelComment: '/partnerTravel/deleteComment', // 删除约伴出游评论
  partnerLike: '/partnerTravel/like', // 喜欢不喜欢约伴出游
  partnerFollow: '/partnerTravel/follow', // 关注不关注约伴出游
  partnerApplyList: '/partnerTravel/applyList', // 查询参与人列表
  hotDestination: '/partnerTravel/hotDestination', // 热门目的地
  partnerApply: '/partnerTravel/apply', // 报名约伴出游
  partnerCancelApply: '/partnerTravel/cancelApply', // 取消报名约伴出游
  labelList: '/guidedEscort/labelList', // 查询服务亮点
  saveGuide: '/guidedEscort/save', // 保存向导陪游产品
  myGuide: '/guidedEscort/ajaxPage', // 旅游达人产品列表
  updateStatus: '/guidedEscort/updateStatus', // 改变达人产品状态
  guideDetail: '/guidedEscort/detail', // 向导陪游详情
  darenDetail: '/travelTalent/detail', // 达人详情
  guideOrder: '/guidedEscort/order/makeOrder', // 向导陪游下单
  guideOrderList: '/guidedEscort/order/ajaxPage', // 向导陪游订单列表
  queryPageContent: '/main/queryPageContent', // 达人介绍
  queryHotServiceCity: '/travelTalent/queryHotServiceCity', // 查询服务地区列表
  saveTravelNote: '/travelNote/save', // 保存游记
  travelNoteList: '/travelNote/ajaxPage', // 查看游记列表
  forwardTras: '/travelNote/forward', // 转发游记
  forwardLook: '/casualLook/forward', // 转发随便看
  myTravelNoteList: '/travelNote/myAjaxPage', // 查看我的游记列表
  travelNoteDetail: '/travelNote/detail', // 游记详情
  travelNoteLike: '/travelNote/like', // 游记喜欢
  travelNotecomment: '/travelNote/comment', // 游记评论
  travelNotecommentList: '/travelNote/ajaxCommentPage', // 游记评论列表
  travelNotefollow: '/travelNote/follow', // 游记收藏
  traNoteDelComment: '/travelNote/deleteComment', // 删除游记评论
  deleteTravelNote: '/travelNote/delete', // 删除游记
  travelTalentTop: '/travelTalent/ajaxPage', // 查询向导Top
  travelNoteDelComment: '/travelNote/deleteComment', // 游记删除评论
  guideUpdateStatus: '/guidedEscort/order/updateStatus', // 向导陪游变更状态
  verifyRefund: '/guidedEscort/order/verifyRefund', // 向导陪游退款申请
  bankList: '/customer/bank/ajaxPage', // 银行卡列表
  withDrawal: '/customerWithdrawal/withdrawal', // 申请提现
  withDrawalList: '/customerWithdrawal/ajaxPage', // 提现列表
  queryFollowList: '/customer/queryFollowList', // 查询关注列表
  couponList: '/coupon/ajaxPage', // 优惠券列表
  receiveCoupon: '/coupon/receive', // 领取优惠券
  getMyCouponList: '/coupon/receiveList', // 我的优惠券
  couponCount: '/coupon/couponCount', // 已领取优惠券数量
  getCouponList: '/travel/order/getCouponList', // 查询可用的优惠券
  signIn: '/customer/signIn' // 签到获取积分
}

export default API
